### ISSUE TITLE
The endpoint /apps/?cursor=0&q=&a= is not filtering by is_active.

### ISSUE THREAD

**Issue by dekrust** [zustack/iron-stream.backend#2]
The current implementation of the endpoint /apps/?cursor=0&q=&a= fails to apply the is_active filter. As a result, the API does not correctly return results based on the is_active status.

**Comment by agustfricke** [comment]
Fixed: https://github.com/zustack/iron-stream.backend/commit/ec4da3efda15143f307ea2a6e3e3780ae03eb1b6

**Comment by agustfricke** [comment]
fixed: https://github.com/zustack/iron-stream.backend/commit/ec4da3efda15143f307ea2a6e3e3780ae03eb1b6
